"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class hopper_data_lcmt(object):

    __slots__ = ["q", "qd", "tauIq"]

    __typenames__ = ["float", "float", "float"]

    __dimensions__ = [[3], [3], [3]]

    def __init__(self):
        self.q = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.qd = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.tauIq = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(hopper_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.q[:3]))
        buf.write(struct.pack('>3f', *self.qd[:3]))
        buf.write(struct.pack('>3f', *self.tauIq[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != hopper_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return hopper_data_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = hopper_data_lcmt()
        self.q = struct.unpack('>3f', buf.read(12))
        self.qd = struct.unpack('>3f', buf.read(12))
        self.tauIq = struct.unpack('>3f', buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if hopper_data_lcmt in parents: return 0
        tmphash = (0x210118c66e5a8665) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if hopper_data_lcmt._packed_fingerprint is None:
            hopper_data_lcmt._packed_fingerprint = struct.pack(">Q", hopper_data_lcmt._get_hash_recursive([]))
        return hopper_data_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", hopper_data_lcmt._get_packed_fingerprint())[0]

