"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class hopper_cmd_lcmt(object):

    __slots__ = ["tau_ff", "q_des", "qd_des", "kp_joint", "kd_joint"]

    __typenames__ = ["float", "float", "float", "float", "float"]

    __dimensions__ = [[3], [3], [3], [3], [3]]

    def __init__(self):
        self.tau_ff = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.q_des = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.qd_des = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.kp_joint = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.kd_joint = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(hopper_cmd_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.tau_ff[:3]))
        buf.write(struct.pack('>3f', *self.q_des[:3]))
        buf.write(struct.pack('>3f', *self.qd_des[:3]))
        buf.write(struct.pack('>3f', *self.kp_joint[:3]))
        buf.write(struct.pack('>3f', *self.kd_joint[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != hopper_cmd_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return hopper_cmd_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = hopper_cmd_lcmt()
        self.tau_ff = struct.unpack('>3f', buf.read(12))
        self.q_des = struct.unpack('>3f', buf.read(12))
        self.qd_des = struct.unpack('>3f', buf.read(12))
        self.kp_joint = struct.unpack('>3f', buf.read(12))
        self.kd_joint = struct.unpack('>3f', buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if hopper_cmd_lcmt in parents: return 0
        tmphash = (0x82ae6452a353a6c9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if hopper_cmd_lcmt._packed_fingerprint is None:
            hopper_cmd_lcmt._packed_fingerprint = struct.pack(">Q", hopper_cmd_lcmt._get_hash_recursive([]))
        return hopper_cmd_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", hopper_cmd_lcmt._get_packed_fingerprint())[0]

