/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class hopper_cmd_lcmt implements lcm.lcm.LCMEncodable
{
    /**
     * LCM Type: float[3]
     */
    public float tau_ff[];

    /**
     * LCM Type: float[3]
     */
    public float q_des[];

    /**
     * LCM Type: float[3]
     */
    public float qd_des[];

    /**
     * LCM Type: float[3]
     */
    public float kp_joint[];

    /**
     * LCM Type: float[3]
     */
    public float kd_joint[];

 
    public hopper_cmd_lcmt()
    {
        tau_ff = new float[3];
        q_des = new float[3];
        qd_des = new float[3];
        kp_joint = new float[3];
        kd_joint = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x82ae6452a353a6c9L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.hopper_cmd_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.hopper_cmd_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.tau_ff[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.q_des[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.qd_des[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.kp_joint[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.kd_joint[a]); 
        }
 
    }
 
    public hopper_cmd_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public hopper_cmd_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.hopper_cmd_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.hopper_cmd_lcmt o = new lcmtypes.hopper_cmd_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.tau_ff = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.tau_ff[a] = ins.readFloat();
        }
 
        this.q_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.q_des[a] = ins.readFloat();
        }
 
        this.qd_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.qd_des[a] = ins.readFloat();
        }
 
        this.kp_joint = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.kp_joint[a] = ins.readFloat();
        }
 
        this.kd_joint = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.kd_joint[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.hopper_cmd_lcmt copy()
    {
        lcmtypes.hopper_cmd_lcmt outobj = new lcmtypes.hopper_cmd_lcmt();
        outobj.tau_ff = new float[(int) 3];
        System.arraycopy(this.tau_ff, 0, outobj.tau_ff, 0, 3); 
        outobj.q_des = new float[(int) 3];
        System.arraycopy(this.q_des, 0, outobj.q_des, 0, 3); 
        outobj.qd_des = new float[(int) 3];
        System.arraycopy(this.qd_des, 0, outobj.qd_des, 0, 3); 
        outobj.kp_joint = new float[(int) 3];
        System.arraycopy(this.kp_joint, 0, outobj.kp_joint, 0, 3); 
        outobj.kd_joint = new float[(int) 3];
        System.arraycopy(this.kd_joint, 0, outobj.kd_joint, 0, 3); 
        return outobj;
    }
 
}

