/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class motor_pwm_lcmt implements lcm.lcm.LCMEncodable
{
    public long timestamp;

    /**
     * LCM Type: float[6]
     */
    public float pwm_values[];

    /**
     * 修改为6个PWM通道
     */
    public float roll_error;

    public float pitch_error;

    public float roll_output;

    public float pitch_output;

    public int control_mode;

 
    public motor_pwm_lcmt()
    {
        pwm_values = new float[6];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xdf22cdfdd18ddca1L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.motor_pwm_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.motor_pwm_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        for (int a = 0; a < 6; a++) {
            outs.writeFloat(this.pwm_values[a]); 
        }
 
        outs.writeFloat(this.roll_error); 
 
        outs.writeFloat(this.pitch_error); 
 
        outs.writeFloat(this.roll_output); 
 
        outs.writeFloat(this.pitch_output); 
 
        outs.writeInt(this.control_mode); 
 
    }
 
    public motor_pwm_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public motor_pwm_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.motor_pwm_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.motor_pwm_lcmt o = new lcmtypes.motor_pwm_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.pwm_values = new float[(int) 6];
        for (int a = 0; a < 6; a++) {
            this.pwm_values[a] = ins.readFloat();
        }
 
        this.roll_error = ins.readFloat();
 
        this.pitch_error = ins.readFloat();
 
        this.roll_output = ins.readFloat();
 
        this.pitch_output = ins.readFloat();
 
        this.control_mode = ins.readInt();
 
    }
 
    public lcmtypes.motor_pwm_lcmt copy()
    {
        lcmtypes.motor_pwm_lcmt outobj = new lcmtypes.motor_pwm_lcmt();
        outobj.timestamp = this.timestamp;
 
        outobj.pwm_values = new float[(int) 6];
        System.arraycopy(this.pwm_values, 0, outobj.pwm_values, 0, 6); 
        outobj.roll_error = this.roll_error;
 
        outobj.pitch_error = this.pitch_error;
 
        outobj.roll_output = this.roll_output;
 
        outobj.pitch_output = this.pitch_output;
 
        outobj.control_mode = this.control_mode;
 
        return outobj;
    }
 
}

