"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class hopper_nav_cmd_lcmt(object):

    __slots__ = ["utime", "v_xy_w", "active", "wp_index", "dist_to_wp"]

    __typenames__ = ["int64_t", "float", "int8_t", "int8_t", "float"]

    __dimensions__ = [None, [2], None, None, None]

    def __init__(self):
        self.utime = 0
        """
        High-level navigation command from lidar_perception/patrol.py.
        lcm_controller uses this INSTEAD of the gamepad stick while patrol
        mode is engaged (Y button); stick motion / B always wins back.
        LCM Type: int64_t
        """

        self.v_xy_w = [ 0.0 for dim0 in range(2) ]
        """
        publish time (us)
        LCM Type: float[2]
        """

        self.active = 0
        """
        desired horizontal velocity in map frame (m/s)
        LCM Type: int8_t
        """

        self.wp_index = 0
        """
        1 = patrol wants control (fresh + valid)
        LCM Type: int8_t
        """

        self.dist_to_wp = 0.0
        """
        current waypoint index (status/debug)
        LCM Type: float
        """


    def encode(self):
        buf = BytesIO()
        buf.write(hopper_nav_cmd_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>2f', *self.v_xy_w[:2]))
        buf.write(struct.pack(">bbf", self.active, self.wp_index, self.dist_to_wp))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != hopper_nav_cmd_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return hopper_nav_cmd_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = hopper_nav_cmd_lcmt()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.v_xy_w = struct.unpack('>2f', buf.read(8))
        self.active, self.wp_index, self.dist_to_wp = struct.unpack(">bbf", buf.read(6))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if hopper_nav_cmd_lcmt in parents: return 0
        tmphash = (0x5501cde571b88ee) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if hopper_nav_cmd_lcmt._packed_fingerprint is None:
            hopper_nav_cmd_lcmt._packed_fingerprint = struct.pack(">Q", hopper_nav_cmd_lcmt._get_hash_recursive([]))
        return hopper_nav_cmd_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", hopper_nav_cmd_lcmt._get_packed_fingerprint())[0]

