"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class hopper_odom_lcmt(object):

    __slots__ = ["utime", "pos", "vel", "quat", "rpy", "localized", "quality"]

    __typenames__ = ["int64_t", "float", "float", "float", "float", "int8_t", "int8_t"]

    __dimensions__ = [None, [3], [3], [4], [3], None, None]

    def __init__(self):
        self.utime = 0
        """
        LiDAR-inertial odometry of the robot BODY frame, expressed in the
        hopper world convention: NED-style, +Z DOWN, x = map-forward.
        Published by lidar_perception/odom_lcm_bridge.py (Point-LIO output,
        extrinsics + FLU/ENU -> FRD/NED conversion already applied).
        LCM Type: int64_t
        """

        self.pos = [ 0.0 for dim0 in range(3) ]
        """
        wall-clock time of the odom estimate (us)
        LCM Type: float[3]
        """

        self.vel = [ 0.0 for dim0 in range(3) ]
        """
        body/COM position in map frame (m, +Z down)
        LCM Type: float[3]
        """

        self.quat = [ 0.0 for dim0 in range(4) ]
        """
        body velocity in map frame (m/s, +Z down)
        LCM Type: float[4]
        """

        self.rpy = [ 0.0 for dim0 in range(3) ]
        """
        body->map attitude, wxyz (FRD body, NED map)
        LCM Type: float[3]
        """

        self.localized = 0
        """
        roll/pitch/yaw of the above (rad, aerospace ZYX)
        LCM Type: int8_t
        """

        self.quality = 0
        """
        1 = map-relocalized (map frame is the SAVED map);
        0 = odometry frame (map origin = power-on pose)
        LCM Type: int8_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(hopper_odom_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>3f', *self.pos[:3]))
        buf.write(struct.pack('>3f', *self.vel[:3]))
        buf.write(struct.pack('>4f', *self.quat[:4]))
        buf.write(struct.pack('>3f', *self.rpy[:3]))
        buf.write(struct.pack(">bb", self.localized, self.quality))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != hopper_odom_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return hopper_odom_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = hopper_odom_lcmt()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.pos = struct.unpack('>3f', buf.read(12))
        self.vel = struct.unpack('>3f', buf.read(12))
        self.quat = struct.unpack('>4f', buf.read(16))
        self.rpy = struct.unpack('>3f', buf.read(12))
        self.localized, self.quality = struct.unpack(">bb", buf.read(2))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if hopper_odom_lcmt in parents: return 0
        tmphash = (0x3f9ade5541888ae4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if hopper_odom_lcmt._packed_fingerprint is None:
            hopper_odom_lcmt._packed_fingerprint = struct.pack(">Q", hopper_odom_lcmt._get_hash_recursive([]))
        return hopper_odom_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", hopper_odom_lcmt._get_packed_fingerprint())[0]

