"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class hopper_data_lcmt(object):

    __slots__ = ["q", "qd", "tauIq", "rm_q", "rm_qd", "rm_iq", "rm_online"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "int8_t"]

    __dimensions__ = [[3], [3], [3], [3], [3], [3], None]

    def __init__(self):
        self.q = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.qd = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.tauIq = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.rm_q = [ 0.0 for dim0 in range(3) ]
        """
        ---- RM M2006/C610 motors (via Pixhawk rm_c610 + px4_dds_bridge) ----
        Output-shaft angle (rad, multi-turn) / speed (rad/s) / torque current (A).
        rm_online: bit i = ESC (i+1) feedback fresh (<100ms).
        LCM Type: float[3]
        """

        self.rm_qd = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.rm_iq = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.rm_online = 0
        """ LCM Type: int8_t """

    def encode(self):
        buf = BytesIO()
        buf.write(hopper_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.q[:3]))
        buf.write(struct.pack('>3f', *self.qd[:3]))
        buf.write(struct.pack('>3f', *self.tauIq[:3]))
        buf.write(struct.pack('>3f', *self.rm_q[:3]))
        buf.write(struct.pack('>3f', *self.rm_qd[:3]))
        buf.write(struct.pack('>3f', *self.rm_iq[:3]))
        buf.write(struct.pack(">b", self.rm_online))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != hopper_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return hopper_data_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = hopper_data_lcmt()
        self.q = struct.unpack('>3f', buf.read(12))
        self.qd = struct.unpack('>3f', buf.read(12))
        self.tauIq = struct.unpack('>3f', buf.read(12))
        self.rm_q = struct.unpack('>3f', buf.read(12))
        self.rm_qd = struct.unpack('>3f', buf.read(12))
        self.rm_iq = struct.unpack('>3f', buf.read(12))
        self.rm_online = struct.unpack(">b", buf.read(1))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if hopper_data_lcmt in parents: return 0
        tmphash = (0x8f00706db6147bc) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if hopper_data_lcmt._packed_fingerprint is None:
            hopper_data_lcmt._packed_fingerprint = struct.pack(">Q", hopper_data_lcmt._get_hash_recursive([]))
        return hopper_data_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", hopper_data_lcmt._get_packed_fingerprint())[0]

