"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class jetson_power_lcmt(object):

    __slots__ = ["timestamp", "vin_v", "iin_a", "pin_w", "vin_min_v", "vin_max_v"]

    __typenames__ = ["int64_t", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.vin_v = 0.0
        """
        us since epoch
        LCM Type: float
        """

        self.iin_a = 0.0
        """
        input rail voltage (V), latest sample
        LCM Type: float
        """

        self.pin_w = 0.0
        """
        input rail current (A), latest sample
        LCM Type: float
        """

        self.vin_min_v = 0.0
        """
        input rail power (W), latest sample
        LCM Type: float
        """

        self.vin_max_v = 0.0
        """
        MIN voltage seen since previous publish (dip detector)
        LCM Type: float
        """


    def encode(self):
        buf = BytesIO()
        buf.write(jetson_power_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qfffff", self.timestamp, self.vin_v, self.iin_a, self.pin_w, self.vin_min_v, self.vin_max_v))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != jetson_power_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return jetson_power_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = jetson_power_lcmt()
        self.timestamp, self.vin_v, self.iin_a, self.pin_w, self.vin_min_v, self.vin_max_v = struct.unpack(">qfffff", buf.read(28))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if jetson_power_lcmt in parents: return 0
        tmphash = (0xcb86b181aa020868) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if jetson_power_lcmt._packed_fingerprint is None:
            jetson_power_lcmt._packed_fingerprint = struct.pack(">Q", jetson_power_lcmt._get_hash_recursive([]))
        return jetson_power_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", jetson_power_lcmt._get_packed_fingerprint())[0]

