"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class rm_esc_data_lcmt(object):

    __slots__ = ["timestamp", "shaft_angle_rad", "shaft_speed_rad_s", "current_raw", "rpm", "angle_raw", "online_mask"]

    __typenames__ = ["int64_t", "float", "float", "int16_t", "int16_t", "int32_t", "int8_t"]

    __dimensions__ = [None, [3], [3], [3], [3], [3], None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.shaft_angle_rad = [ 0.0 for dim0 in range(3) ]
        """
        Accumulated multi-turn OUTPUT shaft angle (rad; M2006 gear 36:1 applied on FC).
        LCM Type: float[3]
        """

        self.shaft_speed_rad_s = [ 0.0 for dim0 in range(3) ]
        """
        Output shaft speed (rad/s).
        LCM Type: float[3]
        """

        self.current_raw = [ 0 for dim0 in range(3) ]
        """
        Actual torque current, raw protocol units (-10000..10000 -> -10..+10 A).
        LCM Type: int16_t[3]
        """

        self.rpm = [ 0 for dim0 in range(3) ]
        """
        Rotor speed (rpm, before gearbox).
        LCM Type: int16_t[3]
        """

        self.angle_raw = [ 0 for dim0 in range(3) ]
        """
        Rotor mechanical angle, 0..8191 (single turn, before gearbox).
        LCM Type: int32_t[3]
        """

        self.online_mask = 0
        """
        Bit i set = ESC i+1 feedback seen within the last 100 ms.
        LCM Type: int8_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(rm_esc_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>3f', *self.shaft_angle_rad[:3]))
        buf.write(struct.pack('>3f', *self.shaft_speed_rad_s[:3]))
        buf.write(struct.pack('>3h', *self.current_raw[:3]))
        buf.write(struct.pack('>3h', *self.rpm[:3]))
        buf.write(struct.pack('>3i', *self.angle_raw[:3]))
        buf.write(struct.pack(">b", self.online_mask))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rm_esc_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rm_esc_data_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = rm_esc_data_lcmt()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.shaft_angle_rad = struct.unpack('>3f', buf.read(12))
        self.shaft_speed_rad_s = struct.unpack('>3f', buf.read(12))
        self.current_raw = struct.unpack('>3h', buf.read(6))
        self.rpm = struct.unpack('>3h', buf.read(6))
        self.angle_raw = struct.unpack('>3i', buf.read(12))
        self.online_mask = struct.unpack(">b", buf.read(1))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if rm_esc_data_lcmt in parents: return 0
        tmphash = (0x11690fe9b066cf8b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if rm_esc_data_lcmt._packed_fingerprint is None:
            rm_esc_data_lcmt._packed_fingerprint = struct.pack(">Q", rm_esc_data_lcmt._get_hash_recursive([]))
        return rm_esc_data_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", rm_esc_data_lcmt._get_packed_fingerprint())[0]

