"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class camera_image_lcmt(object):

    __slots__ = ["timestamp_us", "size", "data"]

    __typenames__ = ["int64_t", "int32_t", "byte"]

    __dimensions__ = [None, None, ["size"]]

    def __init__(self):
        self.timestamp_us = 0
        """ LCM Type: int64_t """
        self.size = 0
        """ LCM Type: int32_t """
        self.data = b""
        """ LCM Type: byte[size] """

    def encode(self):
        buf = BytesIO()
        buf.write(camera_image_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp_us, self.size))
        buf.write(bytearray(self.data[:self.size]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != camera_image_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return camera_image_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = camera_image_lcmt()
        self.timestamp_us, self.size = struct.unpack(">qi", buf.read(12))
        self.data = buf.read(self.size)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if camera_image_lcmt in parents: return 0
        tmphash = (0x6d63fc3e05ec5978) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if camera_image_lcmt._packed_fingerprint is None:
            camera_image_lcmt._packed_fingerprint = struct.pack(">Q", camera_image_lcmt._get_hash_recursive([]))
        return camera_image_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", camera_image_lcmt._get_packed_fingerprint())[0]

