"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class hopper_imu_lcmt(object):

    __slots__ = ["quat", "gyro", "acc", "rpy"]

    __typenames__ = ["float", "float", "float", "float"]

    __dimensions__ = [[4], [3], [3], [3]]

    def __init__(self):
        self.quat = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.gyro = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.acc = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.rpy = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(hopper_imu_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4f', *self.quat[:4]))
        buf.write(struct.pack('>3f', *self.gyro[:3]))
        buf.write(struct.pack('>3f', *self.acc[:3]))
        buf.write(struct.pack('>3f', *self.rpy[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != hopper_imu_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return hopper_imu_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = hopper_imu_lcmt()
        self.quat = struct.unpack('>4f', buf.read(16))
        self.gyro = struct.unpack('>3f', buf.read(12))
        self.acc = struct.unpack('>3f', buf.read(12))
        self.rpy = struct.unpack('>3f', buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if hopper_imu_lcmt in parents: return 0
        tmphash = (0x7de391883333d16a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if hopper_imu_lcmt._packed_fingerprint is None:
            hopper_imu_lcmt._packed_fingerprint = struct.pack(">Q", hopper_imu_lcmt._get_hash_recursive([]))
        return hopper_imu_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", hopper_imu_lcmt._get_packed_fingerprint())[0]

