"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class motor_pwm_lcmt(object):

    __slots__ = ["timestamp", "pwm_values", "roll_error", "pitch_error", "roll_output", "pitch_output", "control_mode"]

    __typenames__ = ["int64_t", "float", "float", "float", "float", "float", "int32_t"]

    __dimensions__ = [None, [6], None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.pwm_values = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.roll_error = 0.0
        """
        修改为6个PWM通道
        LCM Type: float
        """

        self.pitch_error = 0.0
        """ LCM Type: float """
        self.roll_output = 0.0
        """ LCM Type: float """
        self.pitch_output = 0.0
        """ LCM Type: float """
        self.control_mode = 0
        """ LCM Type: int32_t """

    def encode(self):
        buf = BytesIO()
        buf.write(motor_pwm_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>6f', *self.pwm_values[:6]))
        buf.write(struct.pack(">ffffi", self.roll_error, self.pitch_error, self.roll_output, self.pitch_output, self.control_mode))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != motor_pwm_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return motor_pwm_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = motor_pwm_lcmt()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.pwm_values = struct.unpack('>6f', buf.read(24))
        self.roll_error, self.pitch_error, self.roll_output, self.pitch_output, self.control_mode = struct.unpack(">ffffi", buf.read(20))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if motor_pwm_lcmt in parents: return 0
        tmphash = (0xdf22cdfdd18ddca1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if motor_pwm_lcmt._packed_fingerprint is None:
            motor_pwm_lcmt._packed_fingerprint = struct.pack(">Q", motor_pwm_lcmt._get_hash_recursive([]))
        return motor_pwm_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", motor_pwm_lcmt._get_packed_fingerprint())[0]

