"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class rm_esc_cmd_lcmt(object):

    __slots__ = ["timestamp", "current_raw"]

    __typenames__ = ["int64_t", "int16_t"]

    __dimensions__ = [None, [3]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.current_raw = [ 0 for dim0 in range(3) ]
        """
        Per-ESC current command for DJI C610 (M2006), CAN IDs 1..3.
        Raw protocol units: -10000..10000 -> -10..+10 A.
        LCM Type: int16_t[3]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(rm_esc_cmd_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>3h', *self.current_raw[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rm_esc_cmd_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rm_esc_cmd_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = rm_esc_cmd_lcmt()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.current_raw = struct.unpack('>3h', buf.read(6))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if rm_esc_cmd_lcmt in parents: return 0
        tmphash = (0xfbd319c8e7417ed7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if rm_esc_cmd_lcmt._packed_fingerprint is None:
            rm_esc_cmd_lcmt._packed_fingerprint = struct.pack(">Q", rm_esc_cmd_lcmt._get_hash_recursive([]))
        return rm_esc_cmd_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", rm_esc_cmd_lcmt._get_packed_fingerprint())[0]

