"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class wheel_cmd_lcmt(object):

    __slots__ = ["timestamp", "speed_des_rad_s", "enable"]

    __typenames__ = ["int64_t", "float", "int8_t"]

    __dimensions__ = [None, [3], None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.speed_des_rad_s = [ 0.0 for dim0 in range(3) ]
        """
        MOBILE kiwi drive: 3 hub-motor wheels evenly spaced 120 deg apart
        on the base circle, hub axes pointing at the chassis center, so
        each wheel drives tangentially (omni rollers carry the side slip).
        Wheel angular speed command (rad/s), positive = wheel rolls CCW
        about its hub axis as seen from OUTSIDE the chassis.
        LCM Type: float[3]
        """

        self.enable = 0
        """
        1 = drive (upper controller is in MOBILE and enabled);
        0 = coast/stop (every other mode). The Jetson driver must also
        apply its own mode gating (X arms / B cuts), same as rm_iq_des.
        LCM Type: int8_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(wheel_cmd_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>3f', *self.speed_des_rad_s[:3]))
        buf.write(struct.pack(">b", self.enable))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != wheel_cmd_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return wheel_cmd_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = wheel_cmd_lcmt()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.speed_des_rad_s = struct.unpack('>3f', buf.read(12))
        self.enable = struct.unpack(">b", buf.read(1))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if wheel_cmd_lcmt in parents: return 0
        tmphash = (0x9a217431cc2efbd0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if wheel_cmd_lcmt._packed_fingerprint is None:
            wheel_cmd_lcmt._packed_fingerprint = struct.pack(">Q", wheel_cmd_lcmt._get_hash_recursive([]))
        return wheel_cmd_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", wheel_cmd_lcmt._get_packed_fingerprint())[0]

