/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class camera_image_lcmt implements lcm.lcm.LCMEncodable
{
    public long timestamp_us;

    public int size;

    /**
     * LCM Type: byte[size]
     */
    public byte data[];

 
    public camera_image_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x6d63fc3e05ec5978L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.camera_image_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.camera_image_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp_us); 
 
        outs.writeInt(this.size); 
 
        if (this.size > 0)
            outs.write(this.data, 0, (int) size);
 
    }
 
    public camera_image_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public camera_image_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.camera_image_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.camera_image_lcmt o = new lcmtypes.camera_image_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp_us = ins.readLong();
 
        this.size = ins.readInt();
 
        this.data = new byte[(int) size];
        ins.readFully(this.data, 0, (int) size); 
    }
 
    public lcmtypes.camera_image_lcmt copy()
    {
        lcmtypes.camera_image_lcmt outobj = new lcmtypes.camera_image_lcmt();
        outobj.timestamp_us = this.timestamp_us;
 
        outobj.size = this.size;
 
        outobj.data = new byte[(int) size];
        if (this.size > 0)
            System.arraycopy(this.data, 0, outobj.data, 0, (int) this.size); 
        return outobj;
    }
 
}

