/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class hopper_cmd_lcmt implements lcm.lcm.LCMEncodable
{
    /**
     * LCM Type: float[3]
     */
    public float tau_ff[];

    /**
     * LCM Type: float[3]
     */
    public float q_des[];

    /**
     * LCM Type: float[3]
     */
    public float qd_des[];

    /**
     * LCM Type: float[3]
     */
    public float kp_joint[];

    /**
     * LCM Type: float[3]
     */
    public float kd_joint[];

    /**
     * RM M2006/C610 torque-current command (A, -10..+10). Leg-class safety:
     * the Jetson driver forwards this to the Pixhawk ONLY in PD/PWMPD mode
     * (gamepad X arms, B stops); every other mode streams 0 A.
     * LCM Type: float[3]
     */
    public float rm_iq_des[];

    /**
     * RM logical-position initialization: on a 0->nonzero rm_set_zero edge,
     * the Jetson driver chooses its offset so the CURRENT physical shaft
     * position reads rm_zero_at_rad. This changes coordinates only; it does
     * not energize or move the motor.
     */
    public float rm_zero_at_rad;

    public byte rm_set_zero;

 
    public hopper_cmd_lcmt()
    {
        tau_ff = new float[3];
        q_des = new float[3];
        qd_des = new float[3];
        kp_joint = new float[3];
        kd_joint = new float[3];
        rm_iq_des = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x48b12f7526e691baL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.hopper_cmd_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.hopper_cmd_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.tau_ff[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.q_des[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.qd_des[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.kp_joint[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.kd_joint[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.rm_iq_des[a]); 
        }
 
        outs.writeFloat(this.rm_zero_at_rad); 
 
        outs.writeByte(this.rm_set_zero); 
 
    }
 
    public hopper_cmd_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public hopper_cmd_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.hopper_cmd_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.hopper_cmd_lcmt o = new lcmtypes.hopper_cmd_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.tau_ff = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.tau_ff[a] = ins.readFloat();
        }
 
        this.q_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.q_des[a] = ins.readFloat();
        }
 
        this.qd_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.qd_des[a] = ins.readFloat();
        }
 
        this.kp_joint = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.kp_joint[a] = ins.readFloat();
        }
 
        this.kd_joint = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.kd_joint[a] = ins.readFloat();
        }
 
        this.rm_iq_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rm_iq_des[a] = ins.readFloat();
        }
 
        this.rm_zero_at_rad = ins.readFloat();
 
        this.rm_set_zero = ins.readByte();
 
    }
 
    public lcmtypes.hopper_cmd_lcmt copy()
    {
        lcmtypes.hopper_cmd_lcmt outobj = new lcmtypes.hopper_cmd_lcmt();
        outobj.tau_ff = new float[(int) 3];
        System.arraycopy(this.tau_ff, 0, outobj.tau_ff, 0, 3); 
        outobj.q_des = new float[(int) 3];
        System.arraycopy(this.q_des, 0, outobj.q_des, 0, 3); 
        outobj.qd_des = new float[(int) 3];
        System.arraycopy(this.qd_des, 0, outobj.qd_des, 0, 3); 
        outobj.kp_joint = new float[(int) 3];
        System.arraycopy(this.kp_joint, 0, outobj.kp_joint, 0, 3); 
        outobj.kd_joint = new float[(int) 3];
        System.arraycopy(this.kd_joint, 0, outobj.kd_joint, 0, 3); 
        outobj.rm_iq_des = new float[(int) 3];
        System.arraycopy(this.rm_iq_des, 0, outobj.rm_iq_des, 0, 3); 
        outobj.rm_zero_at_rad = this.rm_zero_at_rad;
 
        outobj.rm_set_zero = this.rm_set_zero;
 
        return outobj;
    }
 
}

