/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class hopper_nav_cmd_lcmt implements lcm.lcm.LCMEncodable
{
    /**
     * High-level navigation command from lidar_perception/patrol.py.
     * lcm_controller uses this INSTEAD of the gamepad stick while patrol
     * mode is engaged (Y button); stick motion / B always wins back.
     */
    public long utime;

    /**
     * publish time (us)
     * LCM Type: float[2]
     */
    public float v_xy_w[];

    /**
     * desired horizontal velocity in map frame (m/s)
     */
    public byte active;

    /**
     * 1 = patrol wants control (fresh + valid)
     */
    public byte wp_index;

    /**
     * current waypoint index (status/debug)
     */
    public float dist_to_wp;

 
    public hopper_nav_cmd_lcmt()
    {
        v_xy_w = new float[2];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x05501cde571b88eeL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.hopper_nav_cmd_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.hopper_nav_cmd_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        for (int a = 0; a < 2; a++) {
            outs.writeFloat(this.v_xy_w[a]); 
        }
 
        outs.writeByte(this.active); 
 
        outs.writeByte(this.wp_index); 
 
        outs.writeFloat(this.dist_to_wp); 
 
    }
 
    public hopper_nav_cmd_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public hopper_nav_cmd_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.hopper_nav_cmd_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.hopper_nav_cmd_lcmt o = new lcmtypes.hopper_nav_cmd_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.v_xy_w = new float[(int) 2];
        for (int a = 0; a < 2; a++) {
            this.v_xy_w[a] = ins.readFloat();
        }
 
        this.active = ins.readByte();
 
        this.wp_index = ins.readByte();
 
        this.dist_to_wp = ins.readFloat();
 
    }
 
    public lcmtypes.hopper_nav_cmd_lcmt copy()
    {
        lcmtypes.hopper_nav_cmd_lcmt outobj = new lcmtypes.hopper_nav_cmd_lcmt();
        outobj.utime = this.utime;
 
        outobj.v_xy_w = new float[(int) 2];
        System.arraycopy(this.v_xy_w, 0, outobj.v_xy_w, 0, 2); 
        outobj.active = this.active;
 
        outobj.wp_index = this.wp_index;
 
        outobj.dist_to_wp = this.dist_to_wp;
 
        return outobj;
    }
 
}

