/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class hopper_odom_lcmt implements lcm.lcm.LCMEncodable
{
    /**
     * LiDAR-inertial odometry of the robot BODY frame, expressed in the
     * hopper world convention: NED-style, +Z DOWN, x = map-forward.
     * Published by lidar_perception/odom_lcm_bridge.py (Point-LIO output,
     * extrinsics + FLU/ENU -> FRD/NED conversion already applied).
     */
    public long utime;

    /**
     * wall-clock time of the odom estimate (us)
     * LCM Type: float[3]
     */
    public float pos[];

    /**
     * body/COM position in map frame (m, +Z down)
     * LCM Type: float[3]
     */
    public float vel[];

    /**
     * body velocity in map frame (m/s, +Z down)
     * LCM Type: float[4]
     */
    public float quat[];

    /**
     * body->map attitude, wxyz (FRD body, NED map)
     * LCM Type: float[3]
     */
    public float rpy[];

    /**
     * roll/pitch/yaw of the above (rad, aerospace ZYX)
     */
    public byte localized;

    /**
     * 1 = map-relocalized (map frame is the SAVED map);
     * 0 = odometry frame (map origin = power-on pose)
     */
    public byte quality;

 
    public hopper_odom_lcmt()
    {
        pos = new float[3];
        vel = new float[3];
        quat = new float[4];
        rpy = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3f9ade5541888ae4L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.hopper_odom_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.hopper_odom_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.vel[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.quat[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.rpy[a]); 
        }
 
        outs.writeByte(this.localized); 
 
        outs.writeByte(this.quality); 
 
    }
 
    public hopper_odom_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public hopper_odom_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.hopper_odom_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.hopper_odom_lcmt o = new lcmtypes.hopper_odom_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.pos = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.pos[a] = ins.readFloat();
        }
 
        this.vel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.vel[a] = ins.readFloat();
        }
 
        this.quat = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.quat[a] = ins.readFloat();
        }
 
        this.rpy = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rpy[a] = ins.readFloat();
        }
 
        this.localized = ins.readByte();
 
        this.quality = ins.readByte();
 
    }
 
    public lcmtypes.hopper_odom_lcmt copy()
    {
        lcmtypes.hopper_odom_lcmt outobj = new lcmtypes.hopper_odom_lcmt();
        outobj.utime = this.utime;
 
        outobj.pos = new float[(int) 3];
        System.arraycopy(this.pos, 0, outobj.pos, 0, 3); 
        outobj.vel = new float[(int) 3];
        System.arraycopy(this.vel, 0, outobj.vel, 0, 3); 
        outobj.quat = new float[(int) 4];
        System.arraycopy(this.quat, 0, outobj.quat, 0, 4); 
        outobj.rpy = new float[(int) 3];
        System.arraycopy(this.rpy, 0, outobj.rpy, 0, 3); 
        outobj.localized = this.localized;
 
        outobj.quality = this.quality;
 
        return outobj;
    }
 
}

