/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class jetson_power_lcmt implements lcm.lcm.LCMEncodable
{
    public long timestamp;

    /**
     * us since epoch
     */
    public float vin_v;

    /**
     * input rail voltage (V), latest sample
     */
    public float iin_a;

    /**
     * input rail current (A), latest sample
     */
    public float pin_w;

    /**
     * input rail power (W), latest sample
     */
    public float vin_min_v;

    /**
     * MIN voltage seen since previous publish (dip detector)
     */
    public float vin_max_v;

 
    public jetson_power_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xcb86b181aa020868L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.jetson_power_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.jetson_power_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeFloat(this.vin_v); 
 
        outs.writeFloat(this.iin_a); 
 
        outs.writeFloat(this.pin_w); 
 
        outs.writeFloat(this.vin_min_v); 
 
        outs.writeFloat(this.vin_max_v); 
 
    }
 
    public jetson_power_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public jetson_power_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.jetson_power_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.jetson_power_lcmt o = new lcmtypes.jetson_power_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.vin_v = ins.readFloat();
 
        this.iin_a = ins.readFloat();
 
        this.pin_w = ins.readFloat();
 
        this.vin_min_v = ins.readFloat();
 
        this.vin_max_v = ins.readFloat();
 
    }
 
    public lcmtypes.jetson_power_lcmt copy()
    {
        lcmtypes.jetson_power_lcmt outobj = new lcmtypes.jetson_power_lcmt();
        outobj.timestamp = this.timestamp;
 
        outobj.vin_v = this.vin_v;
 
        outobj.iin_a = this.iin_a;
 
        outobj.pin_w = this.pin_w;
 
        outobj.vin_min_v = this.vin_min_v;
 
        outobj.vin_max_v = this.vin_max_v;
 
        return outobj;
    }
 
}

