/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class rm_esc_data_lcmt implements lcm.lcm.LCMEncodable
{
    public long timestamp;

    /**
     * Accumulated multi-turn OUTPUT shaft angle (rad; M2006 gear 36:1 applied on FC).
     * LCM Type: float[3]
     */
    public float shaft_angle_rad[];

    /**
     * Output shaft speed (rad/s).
     * LCM Type: float[3]
     */
    public float shaft_speed_rad_s[];

    /**
     * Actual torque current, raw protocol units (-10000..10000 -> -10..+10 A).
     * LCM Type: int16_t[3]
     */
    public short current_raw[];

    /**
     * Rotor speed (rpm, before gearbox).
     * LCM Type: int16_t[3]
     */
    public short rpm[];

    /**
     * Rotor mechanical angle, 0..8191 (single turn, before gearbox).
     * LCM Type: int32_t[3]
     */
    public int angle_raw[];

    /**
     * Bit i set = ESC i+1 feedback seen within the last 100 ms.
     */
    public byte online_mask;

 
    public rm_esc_data_lcmt()
    {
        shaft_angle_rad = new float[3];
        shaft_speed_rad_s = new float[3];
        current_raw = new short[3];
        rpm = new short[3];
        angle_raw = new int[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x11690fe9b066cf8bL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.rm_esc_data_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.rm_esc_data_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.shaft_angle_rad[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.shaft_speed_rad_s[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeShort(this.current_raw[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeShort(this.rpm[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeInt(this.angle_raw[a]); 
        }
 
        outs.writeByte(this.online_mask); 
 
    }
 
    public rm_esc_data_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public rm_esc_data_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.rm_esc_data_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.rm_esc_data_lcmt o = new lcmtypes.rm_esc_data_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.shaft_angle_rad = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.shaft_angle_rad[a] = ins.readFloat();
        }
 
        this.shaft_speed_rad_s = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.shaft_speed_rad_s[a] = ins.readFloat();
        }
 
        this.current_raw = new short[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.current_raw[a] = ins.readShort();
        }
 
        this.rpm = new short[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rpm[a] = ins.readShort();
        }
 
        this.angle_raw = new int[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.angle_raw[a] = ins.readInt();
        }
 
        this.online_mask = ins.readByte();
 
    }
 
    public lcmtypes.rm_esc_data_lcmt copy()
    {
        lcmtypes.rm_esc_data_lcmt outobj = new lcmtypes.rm_esc_data_lcmt();
        outobj.timestamp = this.timestamp;
 
        outobj.shaft_angle_rad = new float[(int) 3];
        System.arraycopy(this.shaft_angle_rad, 0, outobj.shaft_angle_rad, 0, 3); 
        outobj.shaft_speed_rad_s = new float[(int) 3];
        System.arraycopy(this.shaft_speed_rad_s, 0, outobj.shaft_speed_rad_s, 0, 3); 
        outobj.current_raw = new short[(int) 3];
        System.arraycopy(this.current_raw, 0, outobj.current_raw, 0, 3); 
        outobj.rpm = new short[(int) 3];
        System.arraycopy(this.rpm, 0, outobj.rpm, 0, 3); 
        outobj.angle_raw = new int[(int) 3];
        System.arraycopy(this.angle_raw, 0, outobj.angle_raw, 0, 3); 
        outobj.online_mask = this.online_mask;
 
        return outobj;
    }
 
}

