/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class rm_esc_cmd_lcmt implements lcm.lcm.LCMEncodable
{
    public long timestamp;

    /**
     * Per-ESC current command for DJI C610 (M2006), CAN IDs 1..3.
     * Raw protocol units: -10000..10000 -> -10..+10 A.
     * LCM Type: int16_t[3]
     */
    public short current_raw[];

 
    public rm_esc_cmd_lcmt()
    {
        current_raw = new short[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xfbd319c8e7417ed7L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.rm_esc_cmd_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.rm_esc_cmd_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeShort(this.current_raw[a]); 
        }
 
    }
 
    public rm_esc_cmd_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public rm_esc_cmd_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.rm_esc_cmd_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.rm_esc_cmd_lcmt o = new lcmtypes.rm_esc_cmd_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.current_raw = new short[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.current_raw[a] = ins.readShort();
        }
 
    }
 
    public lcmtypes.rm_esc_cmd_lcmt copy()
    {
        lcmtypes.rm_esc_cmd_lcmt outobj = new lcmtypes.rm_esc_cmd_lcmt();
        outobj.timestamp = this.timestamp;
 
        outobj.current_raw = new short[(int) 3];
        System.arraycopy(this.current_raw, 0, outobj.current_raw, 0, 3); 
        return outobj;
    }
 
}

