/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class wheel_cmd_lcmt implements lcm.lcm.LCMEncodable
{
    public long timestamp;

    /**
     * MOBILE kiwi drive: 3 hub-motor wheels evenly spaced 120 deg apart
     * on the base circle, hub axes pointing at the chassis center, so
     * each wheel drives tangentially (omni rollers carry the side slip).
     * Wheel angular speed command (rad/s), positive = wheel rolls CCW
     * about its hub axis as seen from OUTSIDE the chassis.
     * LCM Type: float[3]
     */
    public float speed_des_rad_s[];

    /**
     * 1 = drive (upper controller is in MOBILE and enabled);
     * 0 = coast/stop (every other mode). The Jetson driver must also
     * apply its own mode gating (X arms / B cuts), same as rm_iq_des.
     */
    public byte enable;

 
    public wheel_cmd_lcmt()
    {
        speed_des_rad_s = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9a217431cc2efbd0L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.wheel_cmd_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.wheel_cmd_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.speed_des_rad_s[a]); 
        }
 
        outs.writeByte(this.enable); 
 
    }
 
    public wheel_cmd_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public wheel_cmd_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.wheel_cmd_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.wheel_cmd_lcmt o = new lcmtypes.wheel_cmd_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.speed_des_rad_s = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.speed_des_rad_s[a] = ins.readFloat();
        }
 
        this.enable = ins.readByte();
 
    }
 
    public lcmtypes.wheel_cmd_lcmt copy()
    {
        lcmtypes.wheel_cmd_lcmt outobj = new lcmtypes.wheel_cmd_lcmt();
        outobj.timestamp = this.timestamp;
 
        outobj.speed_des_rad_s = new float[(int) 3];
        System.arraycopy(this.speed_des_rad_s, 0, outobj.speed_des_rad_s, 0, 3); 
        outobj.enable = this.enable;
 
        return outobj;
    }
 
}

